### ISSUE TITLE
Should be resolved

### ISSUE THREAD

**Issue by mrsfy** [eliztekcan/Game-of-Life#1]
Kararsızım.

**Comment by deterjan** [comment]
> sLk eLiz

**Comment by eliztekcan** [comment]
slm





#include <stdio.h>
#include <stdlib.h>

int global;

int main(void)
{
printf("================================\n");
printf("Uninitialized variables\n");
printf("================================\n");

int local;

if (local % 2)
{
printf("TRUE : global = %d, local = %d\n", global, local);
}
else
{
printf("FALSE : global = %d, local = %d\n", global, local);
}

return 0;
}


2017-07-14 8:39 GMT+02:00 deterjan <notifications@github.com>:
